### SETUP ART TABELS
GET http://localhost:13000/setup-tables

### GET ART ENTRIES
GET http://localhost:13000/api/art

### INITIALIZE ART DATABASE
GET http://localhost:13000/initialize-database

### GET ART ENTRY BY ID THAT EXISTS
GET http://localhost:13000/api/art/20400

### GET ART ENTRY BY ID THAT DOES NOT EXISTS
GET http://localhost:13000/api/art/1


### CREATE NEW USER (Happy Path)
POST http://localhost:13000/api/users
Content-Type: application/json

{
  "name": "Samuel Butler",
  "age": 29,
  "location": "San Francisco"
}

### TRY TO CREATE USER WITHOUT NAME OR USER ID (Should return 400 Bad Request)
POST http://localhost:13000/api/users
Content-Type: application/json

{
  "age": 30,
  "location": "New York"
}